name: go1x_gin
description: App Description
ignoreFiles: .git
modules:
- name: template
  language: go1.x
  description: Module description
  functions:
  - name: entry
    description: the entry point for the function